# Generated by Django 4.1.7 on 2023-05-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_project_project_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('freelance', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('study', models.CharField(max_length=100)),
            ],
        ),
    ]
