# Generated by Django 4.1.7 on 2023-05-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_about_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about',
            field=models.TextField(default='About'),
        ),
    ]
