# Generated by Django 4.1.7 on 2023-05-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_about_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.CharField(max_length=100)),
                ('clients', models.CharField(max_length=100)),
                ('stars', models.CharField(max_length=100)),
            ],
        ),
    ]
